ALTER TABLE `Media` ADD `owner` INT NOT NULL;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `Media`
  ADD CONSTRAINT `media_owner_id` FOREIGN KEY (`owner`) 
  REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
SET FOREIGN_KEY_CHECKS = 1;
