CREATE TABLE IF NOT EXISTS FavoriteCollection (
    id INT(11) NOT NULL AUTO_INCREMENT,
    user_id INT(11),
    collection_id INT(11),
    PRIMARY KEY (id),
    FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(collection_id) REFERENCES Collection(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;