CREATE TABLE IF NOT EXISTS Media (
    id INT(11) NOT NULL AUTO_INCREMENT,
    file BLOB,
    thumbnail BLOB,
    item_id INT(11), 
    created_date DATETIME NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES Item(id) ON DELETE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;